### ISSUE TITLE
WebApplicationException in JSON file

### ISSUE THREAD

**Issue by LaszloDev** [gabro/car2go-invoicer#3]
The script downloads 12 Json files, with the following content:

`{"constraintViolationMetaInfo":null,"customCode":"0","errorCode":"401","exception":"WebApplicationException"}`

after the 12th file is downloaded the following error occurs:

```
 if (!json.body.StatementHierarchyContainerRTO) {
                 ^

TypeError: Cannot read property 'StatementHierarchyContainerRTO' of undefined
    at fileNames.reduce (/***/car2go-invoicer/index.js:47:18)
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/***/car2go-invoicer/index.js:43:21)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
```

**Comment by gabro** [comment]
Hi, thanks for reporting.
Just to set expectations right, I'm not actively maintaining this, but I'll happily merge a PR that fixes it

**Comment by LaszloDev** [comment]
I see. Don't have the time to look into it myself in the moment.
Does it still work for you? Im using Car2go in Germany to it might be different API here.

**Comment by gabro** [comment]
Unfortunately I barely use car2go myself these days, so something may have changed in the API since the last time I've used this successfully.

The fix might be shorter than manually downloading a bunch of invoices, but I won't likely work on this anytime soon

**Comment by LaszloDev** [comment]
Did find a services that could help me with other invoices too. So I will check it out first:
https://www.invoicefetcher.com
